on:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r tests_requirements.txt
    - name: Lint with flake8
      run: flake8 .

    - name: Run tests with pytest
      run: PYTHONPATH=. pytest

  deploy:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v2
    - name: zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./deploy.zip models lambda_function.py

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-west-2

    - name: deploy
      run: aws lambda update-function-code --function-name=holvi-assignmnent --zip-file=fileb://deploy.zip

  send_message:
   runs-on: ubuntu-latest
   needs: deploy
   if: github.ref == 'refs/heads/master'
   steps:
     - name: send message
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: ${{ github.workflow }} successful!